[package]
name = "website"
version = "0.1.0"
authors = ["awesomearvinder <ArvinderDhan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version = "3.3.2"}
env_logger = "0.8"
